### ISSUE TITLE
T2T v1.0 bed file

### ISSUE THREAD

**Issue by tdfy** [nanopore-wgs-consortium/CHM13#11]
Hello, 

Do you have a bed file or coordinates for v1.0 assembly? I am filtering telomere enriched LR sequences mapped to v1.0. Thank you. 

-Todd

**Comment by skoren** [comment]
Do you mean like the bed file for v0.9 listing which regions were patched and the locations of gaps/rDNA?

**Comment by tdfy** [comment]
Coordinates for telomere regions per chromosome. Example below assuming 2 Mb telomeres on either end of chromosome 1. 

1       248956422       250956422
1       0       2000000

**Comment by skoren** [comment]
Ah OK, I was confused because there is a bed file for v0.9 but no telomere bed file for it. I ran the VGP pipeline (https://github.com/VGP/vgp-assembly/tree/master/pipeline/telomere) for telomere identification and the bed file is attached to this issue.
[chm13.draft_v1.0.telomere.bed.gz](https://github.com/nanopore-wgs-consortium/CHM13/files/5404670/chm13.draft_v1.0.telomere.bed.gz)

**Comment by tdfy** [comment]
Thank you Sergey, take care

**Comment by daphnar** [comment]
Hi Sergey,
Is there a gap/rDNA file like chm13.draft_v1.0.region.bed that is available?
Thank you,
Daphna
